version: "3.8"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: genai
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask:
    build: ./backend
    container_name: flask
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/genai
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network

  angular:
    build: ./frontend
    container_name: angular
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - angular
      - flask
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
