version: "3.8"
services:
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  angular:
    build: ./angular
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
