from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Exercise1(db.Model):
    __tablename__ = 'exercise1'
    id = db.Column(db.Integer, primary_key=True)
    demo_name = db.Column(db.String(255))
    demo_email = db.Column(db.String(255))
    demo_academic = db.Column(db.String(255))
    base_creativity_conf = db.Column(db.Integer)
    base_creativity_freq = db.Column(db.String(50))
    base_creativity_def = db.Column(db.Text)
    ai_used_before = db.Column(db.Boolean)
    ai_tools_list = db.Column(db.Text)
    ai_comfort = db.Column(db.Integer)
    ai_expectations = db.Column(db.Text)
    collab_conf = db.Column(db.Integer)
    collab_role = db.Column(db.String(50))
    collab_value = db.Column(db.Text)
    exp_interest = db.Column(db.Text)
    exp_challenges = db.Column(db.Text)
    exp_diff_ai_human = db.Column(db.Text)
    exp_bias_ai_human = db.Column(db.Text)
    exp_challenge_fairness = db.Column(db.Text)
    exp_message_change = db.Column(db.Text)
    exp_improve = db.Column(db.Text)
    exp_satisfaction = db.Column(db.Integer)
    exp_challenge = db.Column(db.Integer)
    exp_creativity_boost = db.Column(db.Text)
    exp_enjoyment = db.Column(db.Text)
    exp_improvements = db.Column(db.Text)
    ai_helpfulness = db.Column(db.Integer)
    ai_iterations = db.Column(db.Integer)
    ai_strategies = db.Column(db.Text)
    ai_contribution = db.Column(db.String(50))
    ai_learnings = db.Column(db.Text)
    collab_value_post = db.Column(db.Integer)
    collab_feedback = db.Column(db.String(50))
    collab_new_ideas = db.Column(db.Text)
    learn_conf_post = db.Column(db.Integer)
    learn_skills = db.Column(db.Text)
    learn_ai_future = db.Column(db.Integer)
    reflect_creativity_change = db.Column(db.Text)
    reflect_human_ai_role = db.Column(db.Text)
    reflect_future_prep = db.Column(db.Text)
    story_character = db.Column(db.String(255))
    story_setting = db.Column(db.Text)
    story_conflict = db.Column(db.Text)
    story_resolution = db.Column(db.Text)
    story_dialogue = db.Column(db.Text)
    story_moral = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp())